# Generated by Django 2.1.3 on 2019-01-13 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_auto_20181223_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calcoperation',
            name='author',
        ),
    ]
